### ISSUE TITLE
Problem with 

### ISSUE THREAD

**Issue by zonexo** [praksharma/Sunbird#35]
Hi praksharma,

1st of all, thank you for sharing your detailed guide on converting Modulus from docker to apptainer. I really wanted to get pysdf to work but it was so far not successful.

I tried your mtd but I got problem with this part of the code: 

```
echo "Installing CUDA framework for Neural networks"
    pip install git+https://github.com/NVlabs/tiny-cuda-nn/@master#subdirectory=bindings/torch

```

The error is:

```
+ tar xvfz cmake-3.18.2-Linux-x86_64.tar.gz
+ echo 'Installing CUDA framework for Neural networks'
+ pip install git+https://github.com/NVlabs/tiny-cuda-nn/@master#subdirectory=bindings/torch
  Running command git clone -q https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-wvjn6l7b
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status -6:
     command: /opt/conda/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wvjn6l7b/bindi-build-wvjn6l7b/bindings/torch/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.St'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /
         cwd: /tmp/pip-req-build-wvjn6l7b/bindings/torch
    Complete output (2 lines):
    OMP: Error #179: Function Can't open SHM2 failed:
    OMP: System error #38: Function not implemented
    ----------------------------------------
WARNING: Discarding git+https://github.com/NVlabs/tiny-cuda-nn/@master#subdirectory=bindings/torch. Command errored out with exit status l command output.
ERROR: Command errored out with exit status -6: python setup.py egg_info Check the logs for full command output.
FATAL:   While performing build: while running engine: exit status 1

```

Do you know what's wrong? Thanks!

**Comment by praksharma** [comment]
Hi. This tutorial is old and won't work with newer versions of PYSDF. I would suggest using the `apptainer build` or `singularity build` command to build the image. Then simply use the same `apptainer shell` command with all the fancy flags and environment variables. Currently I am doing the same thing.
Another way is to write the build script from scratch. 

In short just follow this guide. https://github.com/praksharma/Sunbird/blob/main/Nvidia%20Modulus/v22.09/1.%20Building%20an%20Apptainer%20image.ipynb

**Comment by zonexo** [comment]
Hi praksharma,

Thanks for the prompt reply. I actually try to do it myself using the conversion too. However, my problem is pysdf. I just can't get it working after the conversion. Did you manage to get it working using the singularity conversion?

The only way I got pysdf worknig is in my own pure ubuntu environment with the original docker image. Even WSL with docker image can't work. But my PC is only RTX2080Ti or RTX3080.

I usually work in my school's cluster or on the cloud like u but they don't allow docker. Singularity is the only option and hence I am trying to use your 22.07 guide (but using v22.09) to get my our apptainer sif.
